export type MaterialType = 
  | 'stone'
  | 'granite'
  | 'polished_granite'
  | 'diorite'
  | 'polished_diorite'
  | 'andesite'
  | 'polished_andesite'
  | 'grass_block'
  | 'dirt'
  | 'coarse_dirt'
  | 'podzol'
  | 'rooted_dirt'
  | 'mud'
  | 'sand'
  | 'red_sand'
  | 'gravel'
  | 'clay'
  | 'sandstone'
  | 'red_sandstone'
  | 'cobblestone'
  | 'bedrock'
  | 'deepslate'
  | 'tuff'
  | 'calcite'
  | 'dripstone_block'
  | 'oak_planks'
  | 'spruce_planks'
  | 'birch_planks'
  | 'jungle_planks'
  | 'acacia_planks'
  | 'dark_oak_planks'
  | 'mangrove_planks'
  | 'oak_log'
  | 'spruce_log'
  | 'birch_log'
  | 'jungle_log'
  | 'acacia_log'
  | 'dark_oak_log'
  | 'mangrove_log'
  | 'coal_ore'
  | 'iron_ore'
  | 'copper_ore'
  | 'gold_ore'
  | 'redstone_ore'
  | 'emerald_ore'
  | 'lapis_lazuli_ore'
  | 'diamond_ore'
  | 'obsidian'
  | 'netherrack'
  | 'nether_quartz_ore'
  | 'basalt'
  | 'blackstone'
  | 'ancient_debris'
  | 'end_stone'
  | 'purpur_block'
  | 'chorus_plant'
  | 'chorus_flower'
  | 'crafting_table'
  | 'furnace'
  | 'blast_furnace'
  | 'smoker'
  | 'anvil'
  | 'grindstone'
  | 'stonecutter'
  | 'smithing_table'
  | 'loom'
  | 'cartography_table'
  | 'bookshelf'
  | 'lectern'
  | 'enchanting_table'
  | 'chest'
  | 'barrel'
  | 'shulker_box'
  | 'ender_chest'
  | 'torch'
  | 'lantern'
  | 'soul_lantern'
  | 'redstone_lamp'
  | 'glowstone'
  | 'sea_lantern'
  | 'jack_olantern'
  | 'glass'
  | 'tinted_glass'
  | 'glass_pane'
  | 'ice'
  | 'packed_ice'
  | 'blue_ice'
  | 'air';

export interface GridCell {
  material: MaterialType;
  collision: 'full' | 'partial' | 'none';
}

export interface Grid {
  cells: GridCell[][];
  width: number;
  height: number;
}

export interface Blueprint {
  levels: Grid[];
  currentLevel: number;
}

export const DEFAULT_GRID_SIZE = 32;

export const MATERIAL_LABELS: Record<MaterialType, string> = {
  stone: 'S',
  granite: 'G',
  polished_granite: 'PG',
  diorite: 'D',
  polished_diorite: 'PD',
  andesite: 'A',
  polished_andesite: 'PA',
  grass_block: 'GB',
  dirt: 'D',
  coarse_dirt: 'CD',
  podzol: 'P',
  rooted_dirt: 'RD',
  mud: 'M',
  sand: 'S',
  red_sand: 'RS',
  gravel: 'G',
  clay: 'C',
  sandstone: 'SS',
  red_sandstone: 'RSS',
  cobblestone: 'C',
  bedrock: 'B',
  deepslate: 'DS',
  tuff: 'T',
  calcite: 'C',
  dripstone_block: 'DB',
  oak_planks: 'OP',
  spruce_planks: 'SP',
  birch_planks: 'BP',
  jungle_planks: 'JP',
  acacia_planks: 'AP',
  dark_oak_planks: 'DOP',
  mangrove_planks: 'MP',
  oak_log: 'OL',
  spruce_log: 'SL',
  birch_log: 'BL',
  jungle_log: 'JL',
  acacia_log: 'AL',
  dark_oak_log: 'DOL',
  mangrove_log: 'ML',
  coal_ore: 'CO',
  iron_ore: 'IO',
  copper_ore: 'CO',
  gold_ore: 'GO',
  redstone_ore: 'RO',
  emerald_ore: 'EO',
  lapis_lazuli_ore: 'LO',
  diamond_ore: 'DO',
  obsidian: 'O',
  netherrack: 'N',
  nether_quartz_ore: 'NQO',
  basalt: 'B',
  blackstone: 'BS',
  ancient_debris: 'AD',
  end_stone: 'ES',
  purpur_block: 'PB',
  chorus_plant: 'CP',
  chorus_flower: 'CF',
  crafting_table: 'CT',
  furnace: 'F',
  blast_furnace: 'BF',
  smoker: 'S',
  anvil: 'A',
  grindstone: 'G',
  stonecutter: 'SC',
  smithing_table: 'ST',
  loom: 'L',
  cartography_table: 'CT',
  bookshelf: 'B',
  lectern: 'L',
  enchanting_table: 'ET',
  chest: 'C',
  barrel: 'B',
  shulker_box: 'SB',
  ender_chest: 'EC',
  torch: 'T',
  lantern: 'L',
  soul_lantern: 'SL',
  redstone_lamp: 'RL',
  glowstone: 'G',
  sea_lantern: 'SL',
  jack_olantern: 'JO',
  glass: 'G',
  tinted_glass: 'TG',
  glass_pane: 'GP',
  ice: 'I',
  packed_ice: 'PI',
  blue_ice: 'BI',
  air: ' '
}; 